version: '3'
services:
  mine-support-claim-service:
    build: .
    image: mine-support-claim-service
    container_name: mine-support-claim-service
    command: npm run start:watch
    environment:
      MESSAGE_HOST: mine-support-message
      MESSAGE_PORT: 5672
      MESSAGE_TRANSPORT: tcp
      CLAIM_MESSAGE_USERNAME: artemis
      CLAIM_MESSAGE_PASSWORD: artemis 
    ports:
      - "3001:3001"
