version: '3'
services:
  mine-support-claim-service:
    build: .
    image: mine-support-claim-service
    container_name: mine-support-claim-service
    command: npm run start:watch
    environment:
      RECEIVE_CLAIM_CONNECTION_STRING: ${RECEIVE_CLAIM_CONNECTION_STRING}
    ports:
      - "3001:3001"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
