version: '3'
services:
  mine-support-claim-service:    
    volumes:
      - ./server/:/usr/src/app/server/
      - ./scripts/:/usr/src/app/scripts/
      - ./index.js:/usr/src/app/index.js
      - ./package.json:/usr/src/app/package.json
