version: '3'
services:
  mine-support-claim-service:
    command: sh -c 'scripts/wait-for.sh mine-support-claim-postgres:5432 -- scripts/wait-for.sh mine-support-message:8161 -- npm run migrate && npm run start:watch'
    depends_on: 
      - mine-support-message
      - mine-support-claim-postgres
    environment:
      MESSAGE_HOST: mine-support-message
      CLAIM_DB_HOST: mine-support-claim-postgres    

  mine-support-message:
    container_name: mine-support-message
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    ports:
      - "8161:8161"
      - "5672:5672"
    volumes:
      - message-queue-data:/var/lib/artemis/data
      - message-queue-tmp:/var/lib/artemis/tmp
      - message-queue-etc:/var/lib/artemis/etc
      - message-queue-etc-override:/var/lib/artemis/etc-override
      - message-queue-lock:/var/lib/artemis/lock

  mine-support-claim-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: claims
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  message-queue-data: {}
  message-queue-tmp: {}
  message-queue-etc: {}
  message-queue-etc-override: {}
  message-queue-lock: {}
  postgres_data: {}
